/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Sun Dec 04 2022 15:52:12 GMT-0600 (Central Standard Time).
 */

 define([
  "js/PanelBase/PanelBaseWithHeader",
  "js/PanelManager/IActivePanel",
  "widgets/Simulator/SimulatorWidget",
  "./SimulatorController",
], function (PanelBaseWithHeader, IActivePanel, SimVizWidget, SimVizControl) {
  "use strict";

  function SimulatorPanel(layoutManager, params) {
    var options = {};
    //set properties from options
    options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = "SimulatorPanel";
    options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

    //call parent's constructor
    PanelBaseWithHeader.apply(this, [options, layoutManager]);

    this._client = params.client;

    //initialize UI
    this._initialize();

    this.logger.debug("ctor finished");
  }

  //inherit from PanelBaseWithHeader
  _.extend(SimulatorPanel.prototype, PanelBaseWithHeader.prototype);
  _.extend(SimulatorPanel.prototype, IActivePanel.prototype);

  SimulatorPanel.prototype._initialize = function () {
    var self = this;

    //set Widget title
    this.setTitle("");

    this.widget = new SimVizWidget(this.logger, this.$el);

    this.widget.setTitle = function (title) {
      self.setTitle(title);
    };

    this.control = new SimVizControl({
      logger: this.logger,
      client: this._client,
      widget: this.widget,
    });

    this.onActivate();
  };

  /* OVERRIDE FROM WIDGET-WITH-HEADER */
  /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
  SimulatorPanel.prototype.onReadOnlyChanged = function (isReadOnly) {
    //apply parent's onReadOnlyChanged
    PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);
  };

  SimulatorPanel.prototype.onResize = function (width, height) {
    this.logger.debug("onResize --> width: " + width + ", height: " + height);
    this.widget.onWidgetContainerResize(width, height);
  };

  /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
  SimulatorPanel.prototype.destroy = function () {
    this.control.destroy();
    this.widget.destroy();

    PanelBaseWithHeader.prototype.destroy.call(this);
    WebGMEGlobal.KeyboardManager.setListener(undefined);
    WebGMEGlobal.Toolbar.refresh();
  };

  SimulatorPanel.prototype.onActivate = function () {
    this.widget.onActivate();
    this.control.onActivate();
    WebGMEGlobal.KeyboardManager.setListener(this.widget);
    WebGMEGlobal.Toolbar.refresh();
  };

  SimulatorPanel.prototype.onDeactivate = function () {
    this.widget.onDeactivate();
    this.control.onDeactivate();
    WebGMEGlobal.KeyboardManager.setListener(undefined);
    WebGMEGlobal.Toolbar.refresh();
  };

  return SimulatorPanel;
});